### ISSUE TITLE
Add support for Azure OpenAI

### ISSUE THREAD

**Issue by mutt0-ds** [memgraph/odin#5]
Hi, I would like to try our the tool but we are using Azure OpenAI, which requires a few settings to change in the environment variables
such as 
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_BASE"] = "https://<your-endpoint.openai.azure.com/"
os.environ["OPENAI_API_KEY"] = "your AzureOpenAI key"
os.environ["OPENAI_API_VERSION"] = "2023-05-15"

is it enough to add them in the Docker Compose file?

**Comment by AlexIchenskiy** [comment]
Thanks for your PR! Currently, adding support for other LLMs isn't possible in ODIN. I've raised Issue #7 to track this feature request, so I'll close your PR in favor of that.
